# Docker context should be "<repo-root>"

FROM node:6.9.3
MAINTAINER OpusCapita

ARG PORT
ENV PORT $PORT

COPY ./packages/server-nodejs /server-nodejs
COPY ./demo /demo

RUN cd demo && ./populate-demo-fs.sh

WORKDIR /demo

EXPOSE $PORT

CMD ["./start.sh"]
