# Docker context should be "<repo-root>"

FROM node:6.9.3
MAINTAINER OpusCapita

RUN mkdir /demo && mkdir /server-nodejs

COPY ./server-nodejs /server-nodejs
COPY ./demo /demo

RUN cd demo && ./populate-demo-fs.sh

WORKDIR /demo

EXPOSE 3020

CMD ["./start.sh"]
