# Docker context should be "<repo-root>"

FROM node:6.9.3
MAINTAINER OpusCapita

ENV HOST 0.0.0.0
ENV PORT 3020

COPY ./packages/server-nodejs /server-nodejs
COPY ./demo /demo

RUN cd demo && ./populate-demo-fs.sh

WORKDIR /demo

EXPOSE $PORT

CMD ["./start.sh"]
