apiVersion: v1
description: A Helm chart for @OpusCapita/filemanager
name: filemanager
version: 0.0.1
home: https://github.com/OpusCapita/filemanager
maintainers:
  - name: Kirill Volkovich
    email: kirill.volkovich@opuscapita.com
    url: https://github.com/kvolkovich-sc
icon: http://test.jcatalog.com/oc-logo-rgb.svg
tillerVersion: ">2.8.0"
